require('lze').load({
    { import = 'boring.plugins.mini' },
    { import = 'boring.plugins.snacks' },
    { import = 'boring.plugins.treesitter' },
    { import = 'boring.plugins.friendly-snippets' },
    { import = 'boring.plugins.lsp' },
    { import = 'boring.plugins.oil' },
    { import = 'boring.plugins.grugfar' },
    { import = 'boring.plugins.neonixdev' },
    { import = 'boring.plugins.conform' },
    { import = 'boring.plugins.lint' },
    { import = 'boring.plugins.undotree' },
    { import = 'boring.plugins.trouble' },
    { import = 'boring.plugins.flatten' },
    { import = 'boring.plugins.fyler' },
    { import = 'boring.plugins.emmet' },
    { import = 'boring.plugins.noice' },
})
