require('lze').load({
    { import = 'boring.plugins.snacks' },
    { import = 'boring.plugins.treesitter' },
    { import = 'boring.plugins.fzf' },
    { import = 'boring.plugins.oil' },
    { import = 'boring.plugins.which_key' },
    { import = 'boring.plugins.conform' },
    { import = 'boring.plugins.lint' },
    { import = 'boring.plugins.git' },
    { import = 'boring.plugins.undotree' },
    { import = 'boring.plugins.todo-comments' },
    { import = 'boring.plugins.trouble' },
    { import = 'boring.plugins.flash' },
    { import = 'boring.plugins.fidget' },
    { import = 'boring.plugins.copilot' },
})
