require('catppuccin').setup({
    flavour = 'mocha',
    term_colors = true,
    dim_inactive = {
        enabled = true,
        shade = 'dark',
        percentage = 0.15,
    },
    custom_highlights = function(colors)
        return {
            BlinkCmpKind = { fg = colors.blue },

            BlinkCmpMenu = { fg = colors.text, bg = colors.base },
            -- BlinkCmpMenuBorder = { fg = colors.overlay0, bg = colors.base },
            BlinkCmpMenuBorder = { fg = colors.blue, bg = colors.base },
            BlinkCmpMenuSelection = { bg = colors.surface0 },
            BlinkCmpLabel = { fg = colors.text },
            BlinkCmpLabelDeprecated = { fg = colors.overlay0, style = { 'strikethrough' } },
            -- BlinkCmpDocBorder = { fg = colors.overlay0, bg = colors.base },
            BlinkCmpDocBorder = { fg = colors.blue, bg = colors.base },
            BlinkCmpDoc = { fg = colors.text, bg = colors.base },
            BlinkCmpSignatureHelpActiveParameter = { fg = colors.mauve },
            BlinkCmpSignatureHelpBorder = { fg = colors.blue },

            SnacksIndent1 = { fg = colors.red },
            SnacksIndent2 = { fg = colors.yellow },
            SnacksIndent3 = { fg = colors.blue },
            SnacksIndent4 = { fg = colors.peach },
            SnacksIndent5 = { fg = colors.green },
            SnacksIndent6 = { fg = colors.mauve },
            SnacksIndent7 = { fg = colors.teal },
            SnacksIndent8 = { fg = colors.maroon },

            BlinkPairsRed = { blend = 0, fg = colors.red },
            BlinkPairsYellow = { blend = 0, fg = colors.yellow },
            BlinkPairsBlue = { blend = 0, fg = colors.blue },
            BlinkPairsOrange = { blend = 0, fg = colors.peach },
            BlinkPairsGreen = { blend = 0, fg = colors.green },
            BlinkPairsViolet = { blend = 0, fg = colors.mauve },
            BlinkPairsCyan = { blend = 0, fg = colors.teal },
        }
    end,
    integrations = {
        blink_cmp = true,
        gitsigns = true,
        dropbar = {
            enabled = true,
            color_mode = true,
        },
        fidget = true,
        fzf = true,
        rainbow_delimiters = true,
        treesitter = true,
        treesitter_context = true,
        indent_blankline = {
            enabled = true,
            scope_color = 'lavender',
            colored_indent_levels = true,
        },
        flash = true,
        mini = {
            enabled = true,
            indentscope_color = 'lavender',
        },
        snacks = { enabled = true, indent_scope_color = 'lavender' },
        which_key = true,
        lsp_saga = true,
        neogit = true,
        noice = true,
        dap = true,
        dap_ui = true,
        render_markdown = true,
        lsp_trouble = true,
        overseer = true,
    },
})
vim.cmd.colorscheme('catppuccin')
